FizzBuzz/Models/FizzBuzzModel.cs
// <copyright file="FizzBuzzModel.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace FizzBuzz.Models
{
    using System.ComponentModel.DataAnnotations;
    using FizzBuzz.Utility.Common;
    using PagedList;

    /// <summary>
    /// FizzBuzzModel.
    /// </summary>
    public class FizzBuzzModel
    {
        /// <summary>
        /// Gets or sets number.
        /// </summary>
        [Required(ErrorMessage = Constants.RequiredErrorMessage)]
        [Range(1, Constants.MaxNumber, ErrorMessage = Constants.EnterNumberMessage)]
        [Display(Name = "Enter Number")]
        public int? Number { get; set; }

        /// <summary>
        /// Gets or sets fizzBuzzListValue.
        /// </summary>
        public IPagedList<string> FizzBuzzListValue { get; set; }
    }
}

FizzBuzz/Controllers/FizzBuzzController.cs
// <copyright file="FizzBuzzController.cs" company="PlaceholderCompany">
// Copyright (c) PlaceholderCompany. All rights reserved.
// </copyright>

namespace FizzBuzz.Controllers
{
    using System.Web.Mvc;
    using FizzBuzz.Models;
    using FizzBuzz.Service.Interface;
    using FizzBuzz.Utility.Common;
    using PagedList;

    /// <summary>
    /// FizzBuzzController.
    /// </summary>
    public class FizzBuzzController : Controller
    {
        private readonly IFizzBuzzService fizzBuzzService;

        private readonly int pageSize = Constants.MaxPageSize;

        /// <summary>
        /// Initializes a new instance of the <see cref="FizzBuzzController"/> class.
        /// </summary>
        /// <param name="fizzBuzzService">IFizzBuzzService.</param>
        public FizzBuzzController(IFizzBuzzService fizzBuzzService)
        {
            this.fizzBuzzService = fizzBuzzService;
        }

        /// <summary>
        /// Get the DisplayFizzBuzz.
        /// </summary>
        /// <returns>FizzBuzzModel.</returns>
        [HttpGet]
        public ActionResult DisplayFizzBuzz()
        {
            return this.View(new FizzBuzzModel());
        }

        /// <summary>
        /// Post the DisplayFizzBuzz.
        /// </summary>
        /// <param name="model">FizzBuzzModel.</param>
        /// <param name="page">Page Number.</param>
        /// <returns>Action with FizzBuzzModel.</returns>
        [HttpPost]
        public ActionResult DisplayFizzBuzz(FizzBuzzModel model, int page = 1)
        {
            if (this.ModelState.IsValid)
            {
                model.FizzBuzzListValue = this.PagedList(model.Number.Value, page);
            }

            return this.View(Constants.ActionName, model);
        }

        /// <summary>
        /// Get the DisplayFizzBuzz on Page Navigation.
        /// </summary>
        /// <param name="number">number.</param>
        /// <param name="page">page.</param>
        /// <returns>Action with FizzBuzzModel.</returns>
        [HttpGet]
        public ActionResult LoadBasedOnPageIndex(int number, int page)
        {
            var model = new FizzBuzzModel
            {
                Number = number,
                FizzBuzzListValue = this.PagedList(number, page),
            };
            return this.View(Constants.ActionName, model);
        }

        private IPagedList<string> PagedList(int number, int pageNumber)
        {
            var resultList = this.fizzBuzzService.GetData(number).ToPagedList(pageNumber, this.pageSize);
            return resultList;
        }
    }
}

FizzBuzz/Views/FizzBuzz/DisplayFizzBuzz.cshtml
@model FizzBuzz.Models.FizzBuzzModel
@using PagedList.Mvc
@{
    ViewBag.Title = "Index Page";
}

<div class="jumbotron">
    @using (Html.BeginForm("DisplayFizzBuzz", "FizzBuzz", FormMethod.Post))
    {
        @Html.LabelFor(m => m.Number, new { @class = "text-primary" })       
        <span></span>
        @Html.TextBoxFor(m => m.Number)
        <input type="submit" class="btn btn-primary btn-sm" value="Submit" />
        @Html.ValidationMessageFor(m => m.Number)

        if (Model.FizzBuzzListValue != null)
        {
            <ul>
                @for (var item = 0; item < Model.FizzBuzzListValue.Count; item++)
                {
                    <li>
                        @foreach (var value in Model.FizzBuzzListValue[item].Split(' '))
                        {
                            <span class="@value">@value</span>
                        }
                    </li>
                }
            </ul>
            <div>
                @Html.PagedListPager(Model.FizzBuzzListValue, page => Url.Action("LoadBasedOnPageIndex", new { Model.Number, page }), PagedListRenderOptions.TwitterBootstrapPager)
            </div>
        }
    }
</div>

FizzBuzz/Views/FizzBuzz/Index.cshtml
@model FizzBuzz.Models.FizzBuzzModel
@using PagedList.Mvc
@{
    ViewBag.Title = "Index Page";
}

<div class="jumbotron">
    @using (Html.BeginForm("Display", "FizzBuzz", FormMethod.Post))
    {
        @Html.Label("Enter Number", new { @class = "text-primary" })
        <span></span>
        @Html.TextBoxFor(m => m.Number)
        <input type="submit" class="btn btn-primary btn-sm" value="Submit" />
        @Html.ValidationMessageFor(m => m.Number) 
        
        if (Model.FizzBuzzListValue != null)
        {
            <ul>
                @for (var item = 0; item < Model.FizzBuzzListValue.Count; item++)
                {
                    <li>
                        @foreach (var value in Model.FizzBuzzListValue[item].Split(' '))
                        {
                            <span class="@value">@value</span>
                        }
                    </li>
                }
            </ul>
            <div>
                @Html.PagedListPager(Model.FizzBuzzListValue, page => Url.Action("LoadBasedOnPageIndex", new { Model.Number, page }), PagedListRenderOptions.TwitterBootstrapPager)
            </div>
        }
    }
</div>

FizzBuzz/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fizz Buzz Demo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Fizz Buzz", "DisplayFizzBuzz", "FizzBuzz", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Fizz Buzz Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>